version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: link-shortener-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=link_shortener_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

